version: '3.3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: gora_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - python-net
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./custom_pg_hba.conf:/etc/postgresql/pg_hba.conf  
      - ./custom_postgresql.conf:/etc/postgresql/postgresql.conf
#    command: ["postgres", "-c", "log_statement=all"]
 #   healthcheck:
  #    test: ["CMD-SHELL", "pg_isready -U postgres"]
  #    interval: 5s
   #   retries: 5
    #  timeout: 5s

  flask_app:
    build: 
      context: .
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
    networks:
      - python-net
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:root@postgres:5432/gora_db

volumes:
  postgres_data:

networks:
  python-net:
    

